### ISSUE TITLE
Not able to install "It seems like you have not downloaded all files"

### ISSUE THREAD

**Issue by ghost** [Joly0/Run-in-Sandbox#1]
I downloaded the zip file, extracted it and allowed the ./Add_Structure.ps1 to be executed. After that i opened a admin powershell and executed the script. Then this messages has been shown:

![image](https://github.com/Joly0/Run-in-Sandbox/assets/84412466/ceeee0c3-edb2-4c85-ae15-c8862cba8c46)

Windows Version: 
![image](https://github.com/Joly0/Run-in-Sandbox/assets/84412466/fb1d2d73-c67a-4ec4-ba22-90276865e0b6)

**Comment by Joly0** [comment]
Hey, i just pushed an update, could you try again. Btw, sorry for the late reply

**Comment by ghost** [comment]
Hey thanks for the update! The message does not appear anymore.
