### ISSUE TITLE
.intunewin context menu option missing

### ISSUE THREAD

**Issue by cwolter97** [Joly0/Run-in-Sandbox#3]
OS: Windows 10 Pro

Ran `Add_Structure.ps1` as admin.

Context menus appear and work for ps1, exe, share folder, etc. Only the intunewin context menu seems to not work.

Add_Structure.ps1 shows that .intunewin should have had it's context-menu option added.

**Comment by Joly0** [comment]
Hey, thanks for noticing and sorry for the late reply. I will look into this as soon as i have time to get back at a computer

**Comment by Joly0** [comment]
Hey, i have tried replicating your issue, but wasnt able. Could you please check, if this path in your registry exists: `Computer\HKEY_CLASSES_ROOT\.intunewin`

Also please send screenshots of those paths, all subfolders and keys in those folders :)

**Comment by Joly0** [comment]
Hey @cwolter97 could you pleaae provide more information? Otherwise i have to close this issue because i cant replicate it.

**Comment by cwolter97** [comment]
@Joly0 I'll be back in office on Monday to provide additional information

**Comment by Joly0** [comment]
Hey @cwolter97 any information you can provide?

**Comment by cwolter97** [comment]
![image](https://github.com/Joly0/Run-in-Sandbox/assets/4241748/e305a5bb-9244-4658-88c3-95d60067ea87)
![image](https://github.com/Joly0/Run-in-Sandbox/assets/4241748/1b1fee96-3f35-47de-a461-f001362b95c4)
![image](https://github.com/Joly0/Run-in-Sandbox/assets/4241748/281382e6-2242-4b24-b1a6-7e4489a7a1ad)
![image](https://github.com/Joly0/Run-in-Sandbox/assets/4241748/f02e5af3-a274-420d-aca9-315ca52d85a9)

**Comment by Joly0** [comment]
Hey, thanks for the screenshots. This looks right and should work. I am not sure why it doesnt work

**Comment by Joly0** [comment]
But i just noticed, there is another thing below there, thats also in the .intunewin folder. Could you send screenshots if whats there aswell?

**Comment by cwolter97** [comment]
There's nothing else in the .intunewin folder
![image](https://github.com/Joly0/Run-in-Sandbox/assets/4241748/b8729d6a-7b3c-4064-8744-40409f379931)

**Comment by Joly0** [comment]
Ahh, sorry. It looked like there was something else.

Tbh, i have no idea whats wrong and why it doesnt work. The registry keys are there and correct.

**Comment by Joly0** [comment]
Could you please check the following registry location:
`Computer\HKEY_CLASSES_ROOT\SystemFileAssociations`
and check if there is a folder named ".intunewin" and if something is in there

**Comment by cwolter97** [comment]
![image](https://github.com/Joly0/Run-in-Sandbox/assets/4241748/dadc57d8-8ebf-4ea8-a57c-f5567bfe6b64)

That folder / entries do seem to be missing!

**Comment by Joly0** [comment]
Okey @cwolter97 could you do me a favor please and try the following:

For these 3 registry paths, add the exact folder structure thats shown in your first screenshots with all keys please. Test each path one by one and see, which ones of these add the context menu entries. Atleast the first and the third should add the context menu entries, but i am not sure.

`HKEY_CURRENT_USER\Software\Classes\.intunewin`

`Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.intunewin`


`Computer\HKEY_CLASSES_ROOT\SystemFileAssociations\.intunewin`

**Comment by cwolter97** [comment]
Adding those keys to the `Computer\HKEY_CLASSES_ROOT\SystemFileAssociations` folder fixed the issue for me!

**Comment by Joly0** [comment]
Hey @cwolter97 thank you for testing. Could you check one last thing for me please. Please go to the windows settings -> Apps -> Default-Apps -> Default Apps by Filetype -> And check here, if anything is configured for .intunewin please and send a screenshot please :)

**Comment by Joly0** [comment]
@cwolter97 Have you had time to look at my previous comment?

**Comment by Sauceonside** [comment]
@Joly0 I had the same issue as the OP, but on Win 11. All information and screenshots were identical. With the same three missing registry paths, I started with the first one, after adding, I tested there was still nothing. Next, I added the third, tested, it should up and worked. I stopped here. When I go to settings>apps>defaultapp>file type, there is no .intunewin. 

  
![image](https://github.com/Joly0/Run-in-Sandbox/assets/129475874/3e70a02f-26b5-4d1a-ac08-f13d4b36d5be)

**Comment by Joly0** [comment]
Hwy @Sauceonside thank you. I still cant replicate this issue on my side, but your provided information is helpful.

I will probably drop the previous registry key i used to add entries for intunewin and use the tested one, as that seems to work everytime.

I will update this issue as soon as the update for this is finished, though it might take a moment, as i am working on a complete rewrite for Run-in-Sandbox code-wise to make it easier to read and understand (hopefully)
