### ISSUE TITLE
Three errors during execution of Powershell script

### ISSUE THREAD

**Issue by anubis-genix** [Joly0/Run-in-Sandbox#4]
Hello,
the script seems to fail with three errors during the execution on my Win11 23H2 Enterprise machine.
Tried to copy and paste the code but the formatting goes crazy. Here's the screenshot instead.
The translation for "Der angegebene Dienst kann nicht gestartet werden. Er ist deaktiviert oder nicht mit aktivierten Geräten verbunden." means "The specified service cannot be started. It is deactivated or not connected to activated devices.".

![grafik](https://github.com/Joly0/Run-in-Sandbox/assets/40500650/0bb75f40-c5bf-4d0d-ad7d-ff99e0620306)

Thanks in advance!

**Comment by Joly0** [comment]
Thx for noticing, i will look into it as soon as possible :)

**Comment by Joly0** [comment]
Ok, i have found the bug for the first issue. It looks like, the used command is dependant on the trustedinstaller service, which might be deactivated on your machine. As i dont want to touch your services and just enable/disable them randomly, i will try to find a different approach to getting the needed information

**Comment by Joly0** [comment]
Hey @anubis-genix could you maybe check this path in your registry please: `Computer\HKEY_CLASSES_ROOT\.ps1` and send a screenshot of this folder and all subfolders aswell as the keys in it

**Comment by Joly0** [comment]
Ok, so i have just pushed an update, which should solve all of your mentioned issues, though please still send a screenshot of the registry from my previous answer.

**Comment by anubis-genix** [comment]
Thanks for looking into that issue. 
Since I didn't know if you need the screenshot from my Sandbox or local machine, I included them both.
Sandbox:
![grafik](https://github.com/Joly0/Run-in-Sandbox/assets/40500650/43bd991b-744a-4f16-a325-54c5654781b2)

Local:
![grafik](https://github.com/Joly0/Run-in-Sandbox/assets/40500650/3170485b-82ac-41cd-b10a-d8a42b4f0e8d)
![grafik](https://github.com/Joly0/Run-in-Sandbox/assets/40500650/9e1d820b-bc72-4a14-be8e-de7f024408a5)

I won't have time to test the update for another 5 hours. I will try to give feedback as soon as possible.

**Comment by Joly0** [comment]
Hey, thanks for the screenshots. I meant your local registry, sorry for not mentioning.

I can see, that you have 2 programs for ps1 extension, so could you please check the paths to both of these?
The path should be something like
`Computer\HKEY_CLASSES_ROOT\AppX......`
And please do this before you test the update :)

**Comment by anubis-genix** [comment]
The first one is: @{19282JackieLiu.Notepads-Beta_1.5.5.0_x64__echhpq9pdbte8?ms-resource://19282JackieLiu.Notepads-Beta/Manifest/PowerShellFileDisplayName}

The second entry: @{Microsoft.WindowsNotepad_11.2402.22.0_x64__8wekyb3d8bbwe?ms-resource://Microsoft.WindowsNotepad/Resources/FileTypeDisplayName_Ps1file}

**Comment by Joly0** [comment]
Hey, thanks. Could you also provide screenshots of those paths in your registry please?
I need to know, if the registry keys for run-in-sandbox got created or not

**Comment by anubis-genix** [comment]
Based on your suggestions, I realize that I'm the one to blame. I have assumed, that this script has to be executed in the Sandbox and not on the host...

**Comment by Joly0** [comment]
Ngl, that is quite funny and tbh i dont know what to say.
The sandbox has more or less no access to the host system and gets deleted when closed, so i thought from the install instructions it should be clear enough, that the script needs to be run on the host, not the sandbox.

I mean, the script changes some registry keys on the host, so you can easily run various filetypes in the sandbox.

I'll close this issue now. If you have any other issue with it, please tell me

**Comment by anubis-genix** [comment]
The Sandbox not having access to the host system and getting deleted when closed, is the main reason why I thought this script was made for. I'm using the Sandbox to check for install and uninstall behaviour of applications before I package them for Intune without cluttering up the main host system. Same goes for unknown Powershell scripts and so on. I would have no problem with having to run the script again and again after every start of the Sandbox. Is it doable to be installed in Sandbox only?

**Comment by Joly0** [comment]
Hm, i am not quite sure what exactly you want to acomplish. 
If you run my script on the host, it adds some registry keys, which in turn add entries to your right click menu for various file types, like .intunewin, .ps1, .exe or .msi.
If you run one of those entries in the right click menu, this script is executed Sources/Run_in_Sandbox/RunInSandbox.ps1 which basically creates a .wsb (windows sandbox) file in your temp directory, fills it with some data and runs it.

So either you execute my script on the host, or you could also take that RunInSandbox.ps1 script and execute thst manually with the needed arguments. But you would still need have all the other files that are needed for the variius file types, in the correct location, where the add_structure.ps1 script copies them to. So in the end, it would be easier to just run that script.

Creating a version of this software, that can be copied inside the sandbox and then be executed there, defeats the purpose of this tool and therefore will probably not be implemented.

So no matter what you do, you have to do changes to the host to use this tool.

**Comment by Joly0** [comment]
Weils für mich gerade etwas einfacher ist das ganze auf deutsch zu erklären:
Das tool wurde erstellt, um vom host aus, per recht klick menü eintrag, diverse dateitypen zu starten, welche dann isoliert in der sandbox ausgeführt werden. Das tool macht dafür nichts, außer such selbst in einen ordner unter c:/programmdata zu "installieren" und ein pasr registry einträge hinzuzufügen, die für die rechtsklick einträge da sind.

Sobald man einen eintrag auswählt, zum beispiel für eine .exe datei, wird vom runinsandbox.ps1 script eine .wsb datei erstellt, die zum beispiel den install ordner von runinsandbox in die sandbox mirrored (read only), zusätzlich den ordner in dem die exe liegt (auch read-only) und halt einen command hinterlegt der ausgeführt wird, sobald die .wsb datei ausgeführt wird. Danach wird die datei ausgeführt, die sandbox startet mit den angegebenen parametern aus der .wsb datei und für den command aus der angegeben wurde.

Es würde also nichts bringen, wenn das tool umgeschrieben würde, um in der sandbox installiert zu werden, da ja dateien vom host von nöten sind.

Ich gehe mal davon aus, dein prozess sieht so aus, dass du die sandbox startest, deine dateien rein kopierst und dann in der sandbox ausführst und danach deine sandbox beendest.

Im endeffekt ergänzt dieses projekt ja nur deinen prozess dadurch, dass du nicht erst die sandbox starten musst un deine dateien reinkopieren musst, dass läuft dann alles automatisch.

Es werden keine dateien auf deinem host system geändert, keine programme installiert odet ähnliches und du kannst in einer kontrollierten und sauberen umgebung deine software testen.

Ich verstehe also gersde nicht ganz warum du dir einen weg wünscht, um das ganze nur in der sandbox auszuführen?

**Comment by anubis-genix** [comment]
Danke für die ausführliche Antwort. Ich habe wohl das Konzept missverstanden und war davon ausgegangen, dass alles ausschließlich in der Sandbox läuft ohne auf dem Host eine Installation/Änderung vornehmen zu müssen. So eindeutig ist die Beschreibung meines Erachtens leider dann doch nicht. 
Ich wollte selbst Kontextmenü-Einträge auf meinem Host vermeiden indem ich, wie du schon korrekt vermutet hast, sämtliche Prozesse in der Sandbox durchführe, um auf meinem System keinen unnötigen 'Müll' zu hinterlassen. Dein Input hat mir den Deckanstoß gegeben mein bisheriges Konzept zu überdenken um von den Vorteilen des Scriptes zu profitieren. Danke nochmals dafür und die Hilfestellung! 
Sollte ich bei der korrekten Handhabung auf einen Bug stoßen, dann melde ich mich gerne wieder ;)

**Comment by Joly0** [comment]
Danke dir und immer gerne. Klar, falls du probleme hast, melde dich bitte direkt. Ich werde mir das problem dann so schnell wie möglich anschauen.

Ich werde mir wohl dann die readme nochmal anschauen und ggfs etwas überarbeiten um das in zukunft noch klarer zu machen :)
